### ISSUE TITLE
Create GitHub Action to verify PEP8 style guidelines

### ISSUE THREAD

**Issue by JeremyEastham** [johndpjr/AgTern#54]
GitHub Actions are a set of instructions that perform a small task on a Linux machine on GitHub's servers. GitHub provides a limited quota of free processing time that should be sufficient for our use case.

Create an action similar to this one to install and run `pre-commit`:
```yaml
name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - name: Install and run pre-commit
      run: |
        echo "Command 1 goes here"
        echo "Command 2 goes here"
        echo "Command 3 goes here"
```
This action will ensure that our formatting is consistent, since it is currently up to each contributor to install and run pre-commit.
